development:
  adapter: 'mongoid'
  clients:
    default:
      database: <%= ENV['DB_NAME'] %>
      hosts:
        - cluster0-shard-00-00-04j5j.mongodb.net:27017
        - cluster0-shard-00-01-04j5j.mongodb.net:27017
        - cluster0-shard-00-02-04j5j.mongodb.net:27017
      options:
        user: <%= ENV['DB_USERNAME'] %>
        password: <%= ENV['DB_PASSWORD'] %>
        auth_source: admin
        ssl: true
        max_pool_size: 1
